#include <stdio.h>  //printf()
#include <stdlib.h> //srand(), rand()
#include <time.h>   //time()

/* operation: fills the `nums' array with random integers.    */
/* preconditions: an integer array and a variable which shows */
/*                its size are passed to the function.        */
/* postconditions: the `nums' array contains a set of random  */
/*                 integers generated by the function.        */
void randomArray(const int size, int nums[size]);

/* operation: sorts the integers in the `nums' array using    */
/*            a quick sort algorithm.                         */
/* preconditions: an integer array containing a set of poss-  */
/*                ibly unsorted integers and the array's size */
/*                are passed to the function.                 */
/* postconditions: the integer array will now contain a set   */
/*                 of sorted integer values.                  */
void smarter_sort(int nums[], const int start, const int end);

/* operation: outputs the integers found in an integer array  */
/* preconditions: an integer array and its size are passed to */
/*                the function.                               */
/* postconditions: the integers in the array are output to    */
/*                 the user in an easy to read form.          */
void printArray(const int size, const int nums[size]);

int main(void)
{
    /*Declaration and initialization*/
    srand(time(NULL));                     //number generator seeded
    const int ARRAYSIZE = (rand()%30) + 5; //random size between 1 and 30
    int numbers[ARRAYSIZE];                //array of numbers to be sorted

    /*Array given random integers*/
    randomArray(ARRAYSIZE, numbers);       //array given random integers

    printf("Original:\n");
    printArray(ARRAYSIZE, numbers);        //output array
    smarter_sort(numbers, 0, ARRAYSIZE-1); //sort   array
    printf("Sorted:\n");
    printArray(ARRAYSIZE, numbers);        //output array

    return 0;
}

void randomArray(const int size, int nums[size])
{
    int index; //stores index/counter for the loop

    /*Each element is given a random integer value*/
    for(index=0; index < size; index++)
        nums[index] = rand() % 1000; //random integer between 0 and 999
}

void smarter_sort(int nums[], const int start, const int end)
{
    /*Declaration and initialization of variables*/
    int left = start; //index of element smaller than pivot
    int right = end;  //index of element larger than pivot
    int pivot = nums[(end+start)/2]; //reference number
    int temp;         //used when swapping two elements

    /*Main loop*/
    while(left <= right)
    {
        /*Move to the right until value larger */
        /*than or equal to pivot is found.     */
        while(nums[left] < pivot)
            left++;
        /*Move to the left until value smaller */
        /*than or equal to pivot is found.     */
        while(nums[right] > pivot)
            right--;

        /*If 'left' exceeds 'right', then this */
        /*section of the array has been ordered*/
        if(left > right)
            break;

        /*Swapping numbers at 'left' and 'right'*/
        temp = nums[left];
        nums[left] = nums[right];
        nums[right] = temp;

        /*Moving on to the next elements */
        /*in the list to be considered.  */
        left++;
        right--;
    }
    /*If more than one value to the left of 'left'*/
    if((left-1) > start)
        smarter_sort(nums, start, left-1); //sort left part
    /*If at least one value to the right of 'left'*/
    if(left < end)
        smarter_sort(nums, left, end);     //sort right part
}

void printArray(const int size, const int nums[size])
{
    /*Declaration of variable*/
    int index; //stores index for loop

    /*Output*/
    printf("{");
    for(index=0; index < size-1; index++)
        printf("%d, ", nums[index]);
    printf("%d}\n", nums[size-1]);
}
