#include <stdio.h>  //printf(), puts(), getchar()
#include <stdlib.h> //srand(), rand(), malloc(), free()
#include <time.h>   //clock(), clock_t, CLOCKS_PER_SEC

#include "Quick.h"
#include "Insertion.h"

/* operation: fills the `nums' array with random integers.    */
/* preconditions: an integer array and a variable which shows */
/*                its size are passed to the function.        */
/* postconditions: the `nums' array contains a set of random  */
/*                 integers generated by the function.        */
void randomArray(const int size, int nums[size]);

/* operation: checks that the integers in an array are sorted */
/* preconditions: an integer array and its size are passed to */
/*                the function.                               */
/* postconditions: an output indicates whether the sort was   */
/*                 verified or found to be incorrect.         */
void tester(const int size, const int nums[size]);

/* operation: calculates and outputs the time passed from a   */
/*            starting time indicated by the argument and the */
/*            current time.                                   */
/* preconditions: a pre-calculated starting time is passed to */
/*                the function.                               */
/* postconditions: an output indicates the time passed from   */
/*                 'start' till the current time.             */
void calcTime(const clock_t start);

int main(void)
{
    /*Declaration and initialization*/
    clock_t start;          //holds the starting time for process timings
    srand ( time(NULL) );   //random number generator seeded
    const int SIZE[] = {10,100,1000,5000,10000};

    int index;
    for(index = 0; index < 5; index++)
    {
        /*Pointer to an integer is allocated memory for elements*/
        int *numbers = malloc(SIZE[index]*sizeof(int));

        /*Insertion sort*/
        printf("Insertion sort with array of size %d;\n", SIZE[index]);
        randomArray(SIZE[index], numbers); //array given random integers
        start = clock();                   //record starting time
        naive_sort(SIZE[index], numbers);  //sort array
        calcTime(start);                   //calculate time taken
        tester(SIZE[index], numbers);      //verify sort

        printf("\n");

        /*Quick sort*/
        printf("Quick sort with array of size %d;\n", SIZE[index]);
        randomArray(SIZE[index], numbers); //array given random integers
        start = clock();                   //record starting time
        smarter_sort(numbers, 0, SIZE[index]-1); //sort array
        calcTime(start);                   //calculate time taken
        tester(SIZE[index], numbers);      //verify sort

        if(index != 4)
        {
            puts("\nPress ENTER to do the next pair of sorts...");
            while(getchar() != '\n'); //remove all extra characters
        }

        /*Memory allocated is freed*/
        free(numbers);
    }
    return 0;
}

void randomArray(const int size, int nums[size])
{
    int index; //stores index/counter for the loop

    /*Each element is given a random integer value*/
    for(index=0; index < size; index++)
        nums[index] = rand() % 1000; //random integer between 0 and 999
}

void tester(const int size, const int nums[size])
{
    /*Declaration of variable*/
    int index; //stores array counter/index

    /*Tester loop*/
    for(index=0; index < size-1; index++)
    {
        /*Check if a number is followed by a smaller one*/
        if(nums[index] > nums[index+1])
        {
            printf("Sort incorrect.\n");
            return;
        }
    }
    /*Since no number was followed by a smaller one */
    /*the array is hence sorted and was verified.   */
    printf("Sort verified.\n");
}

void calcTime(const clock_t start)
{
    /*Calculating the difference*/
    clock_t diff = clock() - start;
    /*Outputting the difference*/
    printf("Time taken: %lf msec. ", diff*1000.0/CLOCKS_PER_SEC);
}
