#include <stdio.h>  //printf(), put()
#include <stdlib.h> //srand(), rand()
#include <time.h>   //time()

/* operation: fills the `nums' array with random integers.    */
/* preconditions: an integer array and a variable which shows */
/*                its size are passed to the function.        */
/* postconditions: the `nums' array contains a set of random  */
/*                 integers generated by the function.        */
void randomArray(const int size, int nums[size]);

/* operation: sorts the integers in the `nums' array using    */
/*            an insertion sort algorithm.                    */
/* preconditions: an integer array containing a set of poss-  */
/*                ibly unsorted integers and the array's size */
/*                are passed to the function.                 */
/* postconditions: the integer array will now contain a set   */
/*                 of sorted integer values.                  */
void naive_sort(const int size, int nums[size]);

/* operation: outputs the integers found in an integer array. */
/* preconditions: an integer array and its size are passed to */
/*                the function.                               */
/* postconditions: the integers in the array are output to    */
/*                 the user in an easy to read form.          */
void printArray(const int size, const int nums[size]);

int main(void)
{
    /*Declaration and initialization*/
    srand(time(NULL));                     //number generator seeded
    const int ARRAYSIZE = (rand()%30) + 1; //random size between 1 and 30
    int numbers[ARRAYSIZE];                //holds numbers to be sorted

    /*Array given random integers*/
    randomArray(ARRAYSIZE, numbers);       //array given random integers

    puts("Original: ");
    printArray(ARRAYSIZE, numbers); //output array
    naive_sort(ARRAYSIZE, numbers); //sort   array
    puts("Sorted: ");
    printArray(ARRAYSIZE, numbers); //output array

    return 0;
}

void randomArray(const int size, int nums[size])
{
    int index; //stores array index in the loop

    /*Each element is given a random integer value*/
    for(index=0; index < size; index++)
        nums[index] = rand() % 1000; //random integer between 0 and 999
}

void naive_sort(const int size, int nums[size])
{
    /*Declaration of variables*/
    int index1;     //outer loop index
    int index2;     //inner loop index
    int tempInt;    //stores value of index1'th element

    /*Main sort loop*/
    for(index1=1; index1 < size; index1++)
    {
        tempInt = nums[index1]; //current element stored
        index2 = index1;        //index copied to leave index1 unchanged

        /*Inner sort loop*/
        while(index2 > 0 && nums[index2-1] > tempInt)
        {
            nums[index2] = nums[index2-1]; //element shifted to the right
            index2--;
        }
        nums[index2]=tempInt; //vacated element taken up by tempInt
    }
}

void printArray(const int size, const int nums[size])
{
    /*Declaration of variable*/
    int index; //stores index for loop

    /*Output*/
    printf("{");
    for(index=0; index < size-1; index++)
        printf("%d, ", nums[index]);
    printf("%d}\n", nums[size-1]);
}
